version: '3'
services:
  web:
    container_name: paapi-container
    build: .
    ports:
      - "8080:8080"
      - "44300:44300"
      - "44301:44301"
      - "44302:44302"
      - "44303:44303"
      - "44304:44304"
    volumes: 
      - ./paapi:/work
    working_dir: /work
    tty: true